### PR TITLE
Fix handling of fragmented terminal background color responses

### LINKED ISSUE #271: Moar enter search mode in Windows Terminal, Zsh, WSL Ubuntu 24.04
When I use moar, it frequently(but not always, sometimes normal) enter Search Mode with "28282":

Image

I'm confused why this happen while it works normal in Windows Terminal, PowerShell, Windows.

The trace information when the issue occurs is as follw:

```
Version     : v1.31.3
LANG        : en_US.UTF-8
TERM        : xterm-256color
MOAR        :
EDITOR      :
TERM_PROGRAM:

GOOS    : linux
GOARCH  : amd64
Compiler: gc
NumCPU  : 16

Stdin  is a terminal: true
Stdout is a terminal: true

time="Feb 22 14:12:31.697169" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:12:31.699020" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:12:31.699058" level=debug msg="Counted 14 lines in 19.32µs at 1.38µs/line"
time="Feb 22 14:12:31.699081" level=info msg="Stream read in 15.274µs"
time="Feb 22 14:12:31.699256" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:12:31.699268" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:12:31.699305" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 22 14:12:31.699327" level=info msg="Entering Twin main loop..."
time="Feb 22 14:12:31.699736" level=trace msg="ttyin high watermark bumped to 16 bytes"
time="Feb 22 14:12:31.699754" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>]11;rgb:2828/28}"
time="Feb 22 14:12:31.699803" level=debug msg="Expected terminal background color event but got {50} after 488.035µs putting back and giving up"
time="Feb 22 14:12:31.699810" level=debug msg="Using style <native>"
time="Feb 22 14:12:31.699823" level=info msg="Pager starting"
time="Feb 22 14:12:31.699876" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>\\}"
time="Feb 22 14:12:31.699935" level=debug msg="No lexer set for highlighting"
time="Feb 22 14:12:31.699942" level=debug msg="highlightFromMemory() took 857.861µs"
time="Feb 22 14:12:31.699944" level=debug msg="Tailing file .condarc"
time="Feb 22 14:12:31.700564" level=info msg="Entering pager main loop..."
time="Feb 22 14:12:31.700569" level=trace msg="Handling rune event '8'/0x0038..."
time="Feb 22 14:12:31.700572" level=debug msg="Unhandled rune keypress '8'/0x00000038"
time="Feb 22 14:12:31.700573" level=trace msg="Handling rune event '/'/0x002f..."
time="Feb 22 14:12:31.700575" level=trace msg="Handling rune event '2'/0x0032..."
time="Feb 22 14:12:31.700700" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:12:31.700716" level=debug msg="Searched 14 lines in 12.314µs at 1365klines/s or 882ns/line"
time="Feb 22 14:12:31.701093" level=trace msg="Handling rune event '8'/0x0038..."
time="Feb 22 14:12:31.702265" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:12:31.702299" level=debug msg="Searched 14 lines in 26.543µs at 570klines/s or 1.898µs/line"
time="Feb 22 14:12:31.702303" level=trace msg="Handling rune event '2'/0x0032..."
time="Feb 22 14:12:31.702308" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:12:31.702317" level=debug msg="Searched 14 lines in 7.212µs at 2176klines/s or 516ns/line"
time="Feb 22 14:12:31.702319" level=trace msg="Handling rune event '8'/0x0038..."
time="Feb 22 14:12:31.702322" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:12:31.702328" level=debug msg="Searched 14 lines in 4.483µs at 3673klines/s or 322ns/line"
time="Feb 22 14:12:31.702330" level=trace msg="Handling rune event '2'/0x0032..."
time="Feb 22 14:12:31.702332" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:12:31.702338" level=debug msg="Searched 14 lines in 4.091µs at 4060klines/s or 293ns/line"
time="Feb 22 14:12:32.605787" level=trace msg="Handling key event 0..."
time="Feb 22 14:12:32.700359" level=trace msg="File .condarc unchanged at 653 bytes, continue tailing"
time="Feb 22 14:12:32.869013" level=trace msg="Handling rune event 'q'/0x0071..."
time="Feb 22 14:12:32.869138" level=info msg="ttyin read error, twin giving up: EOF"
```

I found the message wrote `"Unhandled multi character terminal escape sequence(s): {<0x1b>]11;rgb:2828/28}"`. So I considered the magic number 28282 seems to be related with my background color. Coincidentally, I found my background color is `#282828` since I'm using Gruvbox Dark theme, and its schemes JSON is as follow:

```json
     {
            "background": "#282828",
            "black": "#282828",
            "blue": "#458588",
            "brightBlack": "#928374",
            "brightBlue": "#83A598",
            "brightCyan": "#8EC07C",
            "brightGreen": "#B8BB26",
            "brightPurple": "#D3869B",
            "brightRed": "#FB4934",
            "brightWhite": "#EBDBB2",
            "brightYellow": "#FABD2F",
            "cursorColor": "#EBDBB2",
            "cyan": "#689D6A",
            "foreground": "#EBDBB2",
            "green": "#98971A",
            "name": "Gruvbox Dark",
            "purple": "#B16286",
            "red": "#CC241D",
            "selectionBackground": "#FFFFFF",
            "white": "#A89984",
            "yellow": "#D79921"
        }
```

Then I changed to other scheme like CampBell PowerShell which background color is `#012456` so I can figured out the composition of the magic string. And the searched string transformed to "56562". Its related trace information is as follow:

```
time="Feb 22 14:21:01.232417" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:21:01.234141" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:21:01.234183" level=debug msg="Counted 14 lines in 26.082µs at 1.863µs/line"
time="Feb 22 14:21:01.234204" level=info msg="Stream read in 14.658µs"
time="Feb 22 14:21:01.234363" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:21:01.234373" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:21:01.234410" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 22 14:21:01.234431" level=info msg="Entering Twin main loop..."
time="Feb 22 14:21:01.235559" level=trace msg="ttyin high watermark bumped to 16 bytes"
time="Feb 22 14:21:01.235574" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>]11;rgb:0101/24}"
time="Feb 22 14:21:01.235780" level=debug msg="Expected terminal background color event but got {50} after 1.346616ms putting back and giving up"
time="Feb 22 14:21:01.235787" level=debug msg="Using style <native>"
time="Feb 22 14:21:01.235799" level=info msg="Pager starting"
time="Feb 22 14:21:01.235891" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>\\}"
time="Feb 22 14:21:01.235933" level=debug msg="No lexer set for highlighting"
time="Feb 22 14:21:01.235941" level=debug msg="highlightFromMemory() took 1.733481ms"
time="Feb 22 14:21:01.235943" level=debug msg="Tailing file .condarc"
time="Feb 22 14:21:01.236548" level=info msg="Entering pager main loop..."
time="Feb 22 14:21:01.236553" level=trace msg="Handling rune event '4'/0x0034..."
time="Feb 22 14:21:01.236555" level=debug msg="Unhandled rune keypress '4'/0x00000034"
time="Feb 22 14:21:01.236557" level=trace msg="Handling rune event '/'/0x002f..."
time="Feb 22 14:21:01.236559" level=trace msg="Handling rune event '5'/0x0035..."
time="Feb 22 14:21:01.236688" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:21:01.236705" level=debug msg="Searched 14 lines in 13.428µs at 1240klines/s or 961ns/line"
time="Feb 22 14:21:01.236708" level=trace msg="Handling rune event '6'/0x0036..."
time="Feb 22 14:21:01.236712" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:21:01.236718" level=debug msg="Searched 14 lines in 4.715µs at 3402klines/s or 338ns/line"
time="Feb 22 14:21:01.236720" level=trace msg="Handling rune event '5'/0x0035..."
time="Feb 22 14:21:01.236723" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:21:01.236729" level=debug msg="Searched 14 lines in 4.365µs at 3738klines/s or 313ns/line"
time="Feb 22 14:21:01.236730" level=trace msg="Handling rune event '6'/0x0036..."
time="Feb 22 14:21:01.236733" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:21:01.236739" level=debug msg="Searched 14 lines in 4.11µs at 4006klines/s or 295ns/line"
time="Feb 22 14:21:01.236740" level=trace msg="Handling rune event '2'/0x0032..."
time="Feb 22 14:21:01.236743" level=debug msg="Searching 14 lines across 1 cores with 14 lines per core..."
time="Feb 22 14:21:01.236748" level=debug msg="Searched 14 lines in 3.823µs at 4251klines/s or 274ns/line"
time="Feb 22 14:21:01.888502" level=trace msg="Handling key event 0..."
time="Feb 22 14:21:02.144644" level=trace msg="Handling rune event 'q'/0x0071..."
```

However it seldom works, and the trace information is as follow with background color `#012456`:

```
time="Feb 22 14:21:31.712490" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:21:31.714269" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:21:31.714301" level=debug msg="Counted 14 lines in 6.308µs at 450ns/line"
time="Feb 22 14:21:31.714313" level=info msg="Stream read in 5.061µs"
time="Feb 22 14:21:31.714421" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:21:31.714431" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 14:21:31.714467" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 22 14:21:31.714488" level=info msg="Entering Twin main loop..."
time="Feb 22 14:21:31.715383" level=trace msg="ttyin high watermark bumped to 23 bytes"
time="Feb 22 14:21:31.715404" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>]11;rgb:0101/2424/5656}"
time="Feb 22 14:21:31.715421" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>\\}"
time="Feb 22 14:21:31.765066" level=debug msg="Terminal background color still not detected after 50.572187ms, giving up"
time="Feb 22 14:21:31.765096" level=debug msg="Using style <native>"
time="Feb 22 14:21:31.765230" level=info msg="Pager starting"
time="Feb 22 14:21:31.765326" level=debug msg="No lexer set for highlighting"
time="Feb 22 14:21:31.765337" level=debug msg="highlightFromMemory() took 51.018948ms"
time="Feb 22 14:21:31.765343" level=debug msg="Tailing file .condarc"
time="Feb 22 14:21:31.767491" level=info msg="Entering pager main loop..."
time="Feb 22 14:21:32.161109" level=trace msg="Handling key event 0..."
time="Feb 22 14:21:32.161196" level=info msg="ttyin read error, twin giving up: EOF"
```

Then I found moar work normally in Windows, whether PowerShell or Bash. So I came here for help. Trace information in Windows Terminal, PowerShell, Windows:

```
Version     : v1.31.3
LANG        :
TERM        :
MOAR        :
EDITOR      :
TERM_PROGRAM:

GOOS    : windows
GOARCH  : amd64
Compiler: gc
NumCPU  : 16

Stdin  is a terminal: true
Stdout is a terminal: true

time="Feb 22 14:23:24.970710" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:23:24.981250" level=debug msg="File is assumed to be uncompressed: .condarc"
time="Feb 22 14:23:24.981250" level=debug msg="Counted 14 lines in 0s at 0s/line"
time="Feb 22 14:23:24.981250" level=info msg="Stream read in 0s"
time="Feb 22 14:23:24.981250" level=info msg="ttyin terminal state: &{state:{mode:512}}"
time="Feb 22 14:23:24.981250" level=info msg="ttyout terminal state: &{state:{mode:7}}"
time="Feb 22 14:23:24.981250" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 22 14:23:24.981892" level=info msg="Entering Twin main loop..."
time="Feb 22 14:23:24.981892" level=debug msg="Terminal background color detected as #012456 after 642.2µs"
time="Feb 22 14:23:24.981892" level=debug msg="Using style <native>"
time="Feb 22 14:23:24.981892" level=info msg="Pager starting"
time="Feb 22 14:23:24.981892" level=debug msg="No lexer set for highlighting"
time="Feb 22 14:23:24.981892" level=debug msg="highlightFromMemory() took 642.2µs"
time="Feb 22 14:23:24.981892" level=debug msg="Tailing file .condarc"
time="Feb 22 14:23:24.982450" level=info msg="Entering pager main loop..."
time="Feb 22 14:23:25.630999" level=trace msg="ttyin high watermark bumped to 1 bytes"
time="Feb 22 14:23:25.633225" level=trace msg="Handling rune event 'q'/0x0071..."
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by pilgrimlyieu**
This PR resolves #271.

**Key Changes:**  
1. **Response Buffering**  
   - Added `incompleteResponse` buffer to accumulate partial escape sequences  
   ```diff
   + var incompleteResponse []byte
   ```
2. **Enhanced Parsing Logic**  
   - Modified `parseTerminalBgColorResponse()` to return completion status:  
   ```diff
   - func parseTerminalBgColorResponse(...) *Color
   + func parseTerminalBgColorResponse(...) (*Color, bool)
   ```

**Verification:**  
Tested with Gruvbox Dark some shcemes, no accidental search mode activation observed:  

```
time="Feb 22 20:56:42.453124" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 22 20:56:42.454905" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 22 20:56:42.454928" level=debug msg="Counted 14 lines in 6.478µs at 462ns/line"
time="Feb 22 20:56:42.454941" level=info msg="Stream read in 8.163µs"
time="Feb 22 20:56:42.455058" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 20:56:42.455066" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 22 20:56:42.455098" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 22 20:56:42.455107" level=info msg="Entering Twin main loop..."
time="Feb 22 20:56:42.456013" level=debug msg="Terminal background color detected as #282828 after 890.63µs"
time="Feb 22 20:56:42.456023" level=debug msg="Using style <native>"
time="Feb 22 20:56:42.456038" level=info msg="Pager starting"
time="Feb 22 20:56:42.456150" level=debug msg="No lexer set for highlighting"
time="Feb 22 20:56:42.456156" level=debug msg="highlightFromMemory() took 1.212662ms"
time="Feb 22 20:56:42.456158" level=debug msg="Tailing file /home/fesmoph/.condarc"
time="Feb 22 20:56:42.456774" level=info msg="Entering pager main loop..."
time="Feb 22 20:56:43.063147" level=trace msg="ttyin high watermark bumped to 1 bytes"
time="Feb 22 20:56:43.063314" level=trace msg="Handling rune event 'q'/0x0071..."
time="Feb 22 20:56:43.063419" level=info msg="ttyin read error, twin giving up: EOF"
```

This fix resolves my immediate issue but would benefit from maintainer review. Happy to adjust based on feedback.

### CODE REVIEW

File: twin/screen.go [hunk 1]
```diff
@@ -418,19 +419,32 @@ func (screen *UnixScreen) mainLoop() {
...
-			bg := parseTerminalBgColorResponse(buffer[0:count])
-			if bg != nil {
-				select {
-				case screen.events <- EventTerminalBackgroundDetected{Color: *bg}:
-					// Yay
-				default:
-					// If this happens, consider increasing the channel size in
-					// NewScreen()
-					log.Debugf("Unable to post terminal background color detected event")
+			bg, complete, valid := parseTerminalBgColorResponse(buffer[0:count])
```
Comment (walles) [inline twin/screen.go:429]: Maybe let `incompleteResponse` contain everything we got so far rather than messing with `buffer` here?

I think that will be easier to follow than moving data between `buffer` and `incompleteResponse` higher up here.

File: twin/screen.go [hunk 2]
```diff
@@ -607,28 +621,33 @@ func (screen *UnixScreen) RequestTerminalBackgroundColor() {
 	fmt.Println("\x1b]11;?\x07")
 }
 
-func parseTerminalBgColorResponse(responseBytes []byte) *Color {
+func parseTerminalBgColorResponse(responseBytes []byte) (*Color, bool, bool) {
```
Comment (walles) [inline twin/screen.go:624]: Maybe keep this to just `*Color, bool`?

The first bool (`valid`) is always true when `*Color` is non-nil and the other way around, so having both a `bool` and nullability here is double bookkeeping.

File: twin/screen.go [hunk 3]
```diff
@@ -607,28 +621,33 @@ func (screen *UnixScreen) RequestTerminalBackgroundColor() {
...
 	response = strings.TrimPrefix(response, prefix)
 
-	if !strings.HasSuffix(response, suffix1) && !strings.HasSuffix(response, suffix2) {
+	isComplete := strings.HasSuffix(response, suffix1) || strings.HasSuffix(response, suffix2)
+	if !isComplete && len(responseBytes) < (func() int {
+		if len(sampleResponse1) < len(sampleResponse2) {
+			return len(sampleResponse1)
+		}
+		return len(sampleResponse2)
+	}()) {
```
Comment (walles) [inline twin/screen.go:644]: I think your code is correct, but the same thing can be done without an embedded anonymous function. Not having that function there makes this easier to follow.

```suggestion
	if !isComplete && (len(responseBytes) < len(sampleResponse1) || len(responseBytes) < len(sampleResponse2)) {
```

File: twin/screen.go (hunk 1 above)
Comment (pilgrimlyieu) [reply twin/screen.go]: Done. Refactoring `incompleteResponse` to directly store buffered data.

File: twin/screen.go (hunk 2 above)
Comment (pilgrimlyieu) [reply twin/screen.go]: Done. Simplifying color validation to use `*Color` and `bool` exclusively

File: twin/screen.go (hunk 3 above)
Comment (pilgrimlyieu) [reply twin/screen.go]: Done. Removing embedded anonymous function for clarity.

**Comment by pilgrimlyieu** [comment]
Thank you for the thorough review! I've implemented your suggested changes:

Additional Corrections:
 During finally manual testing, I realized my initial reports omitted some key details:

Windows Terminal, Zsh, WSL Ubuntu 24.04 not always reporing "background color detected" even moar didn't enter search mode. After the fix, moar still sometimes complains that it didn't detect terminal background color thought it no longer enter search mode at the beginning. And I turned my terminal scheme to Gruvbox Light to make it clear:

not-detected

And the trace infomation is as follow:

```
time="Feb 23 10:02:23.314040" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 10:02:23.316171" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 10:02:23.316220" level=debug msg="Counted 14 lines in 6.423µs at 458ns/line"
time="Feb 23 10:02:23.316249" level=info msg="Stream read in 19.919µs"
time="Feb 23 10:02:23.316416" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 10:02:23.316427" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 10:02:23.316465" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 23 10:02:23.316474" level=info msg="Entering Twin main loop..."
time="Feb 23 10:02:23.317149" level=debug msg="Got unexpected prefix in bg color response from terminal: f1/c7c7\x1b\\"
time="Feb 23 10:02:23.317153" level=trace msg="ttyin high watermark bumped to 2 bytes"
time="Feb 23 10:02:23.317158" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>\\}"
time="Feb 23 10:02:23.366719" level=debug msg="Terminal background color still not detected after 50.237805ms, giving up"
time="Feb 23 10:02:23.366733" level=debug msg="Using style <native>"
time="Feb 23 10:02:23.366761" level=debug msg="No lexer set for highlighting"
time="Feb 23 10:02:23.366765" level=debug msg="highlightFromMemory() took 50.514106ms"
time="Feb 23 10:02:23.366767" level=debug msg="Tailing file /home/fesmoph/.condarc"
time="Feb 23 10:02:23.366742" level=info msg="Pager starting"
time="Feb 23 10:02:23.367560" level=info msg="Entering pager main loop..."
time="Feb 23 10:02:24.081307" level=trace msg="Handling rune event 'q'/0x0071..."
```

Writting "Terminal background color still not detected after 50.237805ms, giving up".

However it sometimes does get terminal background color, while the WT, PowerShell, Windows environment always does:

powershell

```
time="Feb 23 10:05:52.716270" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 10:05:52.718142" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 10:05:52.718168" level=debug msg="Counted 14 lines in 7.509µs at 536ns/line"
time="Feb 23 10:05:52.718194" level=info msg="Stream read in 18.957µs"
time="Feb 23 10:05:52.718412" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 10:05:52.718423" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 10:05:52.718469" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 23 10:05:52.718491" level=info msg="Entering Twin main loop..."
time="Feb 23 10:05:52.719473" level=debug msg="Terminal background color detected as #fbf1c7 after 960.462µs"
time="Feb 23 10:05:52.719486" level=debug msg="Using style <tango>"
time="Feb 23 10:05:52.719502" level=info msg="Pager starting"
time="Feb 23 10:05:52.719602" level=debug msg="No lexer set for highlighting"
time="Feb 23 10:05:52.719608" level=debug msg="highlightFromMemory() took 1.410724ms"
time="Feb 23 10:05:52.719609" level=debug msg="Tailing file /home/fesmoph/.condarc"
time="Feb 23 10:05:52.720873" level=info msg="Entering pager main loop..."
time="Feb 23 10:05:53.393218" level=trace msg="ttyin high watermark bumped to 1 bytes"
time="Feb 23 10:05:53.393304" level=trace msg="Handling rune event 'q'/0x0071..."
time="Feb 23 10:05:53.393369" level=info msg="ttyin read error, twin giving up: EOF"
```

This issue seems to exist before this PR so I have no ideas about it. Should this problem be included in this PR too or report it in a new issue?

Please let me know if further adjustments are needed. Your expertise in terminal protocols has been invaluable!

File: twin/screen.go [hunk 4]
```diff
@@ -607,28 +613,28 @@ func (screen *UnixScreen) RequestTerminalBackgroundColor() {
...
 		log.Debug("Got unexpected prefix in bg color response from terminal: ", string(responseBytes))
-		return nil
+		return nil, false // Invalid
 	}
 	response = strings.TrimPrefix(response, prefix)
 
-	if !strings.HasSuffix(response, suffix1) && !strings.HasSuffix(response, suffix2) {
+	isComplete := strings.HasSuffix(response, suffix1) || strings.HasSuffix(response, suffix2)
+	if !isComplete && (len(responseBytes) < len(sampleResponse1) || len(responseBytes) < len(sampleResponse2)) {
+		return nil, true // Incomplete but valid
```
Comment (walles) [inline twin/screen.go:632]: These comments are super helpful!

Comment (walles) [reply twin/screen.go:632]: Maybe log a debug level message here with the text we have received so far?

That might make it easier to figure out what's happening in the not-working cases.

**Comment by walles** [comment]
This looks like the second half of an actual response. Maybe this would get more obvious with logging of incomplete-but-valid prefixes?

```
"Got unexpected prefix in bg color response from terminal: f1/c7c7\x1b\\"
```

File: twin/screen.go [hunk 5]
```diff
@@ -418,20 +419,25 @@ func (screen *UnixScreen) mainLoop() {
...
+						// NewScreen()
+						log.Debugf("Unable to post terminal background color detected event")
+					}
+					expectingTerminalBackgroundColor = false
+					incompleteResponse = nil
 				}
-				expectingTerminalBackgroundColor = false
 				continue
 			}
+			incompleteResponse = nil
```
[the remark this answers is not in the document]
Comment (pilgrimlyieu) [reply twin/screen.go:441]: Done.

File: twin/screen.go (hunk 4 above)
Comment (pilgrimlyieu) [reply twin/screen.go:635]: Done.

**Comment by pilgrimlyieu** [comment]
Hi @walles,  

Acknowledgement & Correction: Upon re-verification, I realized my earlier report about issues reproduction was based on **outdated build artifacts** (my local build cache wasn't properly cleaned). After rebuilding, All cases now handle background queries correctly.

Trace information now:

```
time="Feb 23 23:39:29.576456" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 23:39:29.578207" level=debug msg="File is assumed to be uncompressed: /home/fesmoph/.condarc"
time="Feb 23 23:39:29.578238" level=debug msg="Counted 14 lines in 12.312µs at 879ns/line"
time="Feb 23 23:39:29.578257" level=info msg="Stream read in 13.918µs"
time="Feb 23 23:39:29.578386" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 23:39:29.578396" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:0 Oflag:4 Cflag:191 Lflag:2608 Line:0 Cc:[3 28 127 21 4 0 1 0 17 19 26 0 18 15 23 22 0 0 0] Ispeed:0 Ospeed:0}}}"
time="Feb 23 23:39:29.578434" level=info msg="No known terminal with arrow keys emulation detected, assuming mouse tracking is needed"
time="Feb 23 23:39:29.578443" level=info msg="Entering Twin main loop..."
time="Feb 23 23:39:29.579670" level=debug msg="Terminal bg color response received so far: fbfb/f1"
time="Feb 23 23:39:29.579934" level=debug msg="Terminal bg color response received so far: fbfb/f1f1/c7c7"
time="Feb 23 23:39:29.580431" level=debug msg="Terminal background color detected as #fbf1c7 after 1.963191ms"
time="Feb 23 23:39:29.580441" level=debug msg="Using style <tango>"
time="Feb 23 23:39:29.580454" level=info msg="Pager starting"
time="Feb 23 23:39:29.580583" level=debug msg="No lexer set for highlighting"
time="Feb 23 23:39:29.580588" level=debug msg="highlightFromMemory() took 2.327846ms"
time="Feb 23 23:39:29.580590" level=debug msg="Tailing file /home/fesmoph/.condarc"
time="Feb 23 23:39:29.581802" level=info msg="Entering pager main loop..."
time="Feb 23 23:39:29.989129" level=trace msg="ttyin high watermark bumped to 1 bytes"
time="Feb 23 23:39:29.989227" level=trace msg="Handling rune event 'q'/0x0071..."
```  

This confirms the issue is fully resolved in the current implementation. My apologies for the earlier inaccurate context – appreciate your patience as I navigate these toolchain nuances.

The PR remains ready for final review when convenient.

File: twin/screen.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (pilgrimlyieu) [reply twin/screen.go:441]: This seems to make Go Lint fail. Should I revert this change or remove the assignment of `expectingTerminalBackgroundColor` outside `if` block?

**Comment by pilgrimlyieu** [comment]
Thanks for the suggestion! When implementing your feedback, I encountered a CI linting issue:

```text
Error: twin/screen.go:442:4: ineffectual assignment to expectingTerminalBackgroundColor (ineffassign)
			expectingTerminalBackgroundColor = false
```  

To resolve this, there are two options:  

**Option 1:** Keep original implementation  
```diff
			}
			// Not valid
			incompleteResponse = nil
-           expectingTerminalBackgroundColor = false
		}
```  

*(This is the currently committed version)*  

**Option 2:** Remove assignment outside `if` block
```diff
-		// We only expect this on entry, it's requested right before we start
-		// the main loop in NewScreenWithMouseModeAndColorCount().
-		expectingTerminalBackgroundColor = false
```  

I temporarily chose **Option 1** to keep CI passing, but happy to implement **Option 2** if you prefer that approach. Please advise which direction you'd like me to pursue.

File: twin/screen.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (walles) [reply twin/screen.go:441]: This is done on line 446 as well. Maybe shoot for doing both in the same place?

And I know this was my suggestion :) but in retrospect I agree with the linter that my suggestion was redundant.

**Comment by walles** [comment]
Thanks @pilgrimlyieu, now released:
https://github.com/walles/moar/releases/tag/v1.31.4

**Comment by pilgrimlyieu** [comment]
Just verified v1.31.4 works perfectly now. Thanks for maintaining this brilliant tool!
